name: mat281
channels:
  - conda-forge
  - defaults
dependencies:
  # Jupyter
  - jupyterlab=2.1.3
  - nodejs
  - widgetsnbextension
  # Python kernel
  - altair=4
  - altair_saver
  - ipywidgets=7.5
  - matplotlib
  - numpy
  - pandas=1
  - pandas-profiling
  - pip
  - pillow
  - python=3.7
  - rise
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - sympy
  - vega_datasets
  - xlrd